// <auto-generated />
using System;
using Indotel.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Indotel.Core.Migrations
{
    [DbContext(typeof(IndotelDbContext))]
    [Migration("20260709093736_Fase2D3ReportesHardeningAuth")]
    partial class Fase2D3ReportesHardeningAuth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Indotel.Core.Models.AsignacionFrecuencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("EntidadAsignada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<int>("FrecuenciaRadioelectricaId")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PrestadoraId")
                        .HasColumnType("int");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsoAutorizado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioAsignacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrestadoraId");

                    b.HasIndex("FrecuenciaRadioelectricaId", "Activa");

                    b.ToTable("AsignacionesFrecuencia");
                });

            modelBuilder.Entity("Indotel.Core.Models.Auditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireccionIp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EntidadId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EstadoAnterior")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoNuevo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetodoHttp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioCorreo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioRol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Accion");

                    b.HasIndex("Fecha");

                    b.HasIndex("Entidad", "EntidadId");

                    b.ToTable("Auditorias");
                });

            modelBuilder.Entity("Indotel.Core.Models.Ciudadano", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.ToTable("Ciudadanos");
                });

            modelBuilder.Entity("Indotel.Core.Models.DocumentoReclamacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReclamacionId")
                        .HasColumnType("int");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoContenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DocumentosReclamacion");
                });

            modelBuilder.Entity("Indotel.Core.Models.FrecuenciaRadioelectrica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Banda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RangoFinMHz")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("RangoInicioMHz")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ServicioUso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("RangoInicioMHz", "RangoFinMHz", "Region")
                        .IsUnique();

                    b.ToTable("FrecuenciasRadioelectricas");
                });

            modelBuilder.Entity("Indotel.Core.Models.HistorialReclamacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoAnterior")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoNuevo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReclamacionId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HistorialReclamaciones");
                });

            modelBuilder.Entity("Indotel.Core.Models.LicenciaTecnica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EntidadAsignada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCancelacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("FrecuenciaRadioelectricaId")
                        .HasColumnType("int");

                    b.Property<string>("MotivoCancelacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroLicencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("PrestadoraId")
                        .HasColumnType("int");

                    b.Property<int?>("ResolucionInstitucionalId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioCancelacionId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioCreacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaVencimiento");

                    b.HasIndex("FrecuenciaRadioelectricaId");

                    b.HasIndex("NumeroLicencia")
                        .IsUnique();

                    b.HasIndex("PrestadoraId");

                    b.HasIndex("ResolucionInstitucionalId");

                    b.ToTable("LicenciasTecnicas");
                });

            modelBuilder.Entity("Indotel.Core.Models.MotivoReclamacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TipoReclamacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoReclamacionId", "Nombre")
                        .IsUnique();

                    b.ToTable("MotivosReclamacion");
                });

            modelBuilder.Entity("Indotel.Core.Models.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CiudadanoId")
                        .HasColumnType("int");

                    b.Property<string>("Destinatario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaLectura")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PrestadoraId")
                        .HasColumnType("int");

                    b.Property<int?>("ReclamacionId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CiudadanoId");

                    b.HasIndex("FechaCreacion");

                    b.HasIndex("PrestadoraId");

                    b.HasIndex("ReclamacionId");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("Indotel.Core.Models.Prestadora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Representante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rnc")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Rnc")
                        .IsUnique();

                    b.ToTable("Prestadoras");
                });

            modelBuilder.Entity("Indotel.Core.Models.Reclamacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccionOrdenada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CanalRecepcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CiudadanoId")
                        .HasColumnType("int");

                    b.Property<string>("ComentarioCierre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComentarioResolucion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ConformidadCiudadano")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DiasHabilesSla")
                        .HasColumnType("int");

                    b.Property<bool>("EstaVencida")
                        .HasColumnType("bit");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEnvioPrestadora")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaLimiteRespuesta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaMarcadaVencida")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRespuestaPrestadora")
                        .HasColumnType("datetime2");

                    b.Property<string>("FundamentoResolucion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MontoAjuste")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MotivoCierre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MotivoReclamacionId")
                        .HasColumnType("int");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroExpediente")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PrestadoraId")
                        .HasColumnType("int");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultadoResolucion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServicioTelecomId")
                        .HasColumnType("int");

                    b.Property<int?>("TipoReclamacionId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioCierreId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioResolucionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MotivoReclamacionId");

                    b.HasIndex("NumeroExpediente")
                        .IsUnique();

                    b.HasIndex("TipoReclamacionId");

                    b.ToTable("Reclamaciones");
                });

            modelBuilder.Entity("Indotel.Core.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreadoPorIp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiraEn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRevocacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReemplazadoPorTokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RevocadoPorIp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Indotel.Core.Models.ResolucionInstitucional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DocumentoReclamacionId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaArchivo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroResolucion")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("PrestadoraId")
                        .HasColumnType("int");

                    b.Property<int?>("ReclamacionId")
                        .HasColumnType("int");

                    b.Property<string>("Resumen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoResolucionId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlDocumentoOficial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioAprobacionId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioArchivoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioCreacionId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioPublicacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoReclamacionId");

                    b.HasIndex("Estado");

                    b.HasIndex("NumeroResolucion")
                        .IsUnique();

                    b.HasIndex("PrestadoraId");

                    b.HasIndex("ReclamacionId");

                    b.HasIndex("TipoResolucionId");

                    b.ToTable("ResolucionesInstitucionales");
                });

            modelBuilder.Entity("Indotel.Core.Models.RespuestaPrestadora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentoSoporte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRespuesta")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrestadoraId")
                        .HasColumnType("int");

                    b.Property<int>("ReclamacionId")
                        .HasColumnType("int");

                    b.Property<string>("Respuesta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RespuestasPrestadora");
                });

            modelBuilder.Entity("Indotel.Core.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Indotel.Core.Models.ServicioTelecom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("ServiciosTelecom");
                });

            modelBuilder.Entity("Indotel.Core.Models.SolicitudAutorizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ComentarioRevision")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRechazo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRenovacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRevision")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoRechazo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroSolicitud")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("PrestadoraId")
                        .HasColumnType("int");

                    b.Property<int?>("ResolucionInstitucionalId")
                        .HasColumnType("int");

                    b.Property<string>("SolicitanteNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolicitanteRnc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoAutorizacionId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioResponsableId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("NumeroSolicitud")
                        .IsUnique();

                    b.HasIndex("PrestadoraId");

                    b.HasIndex("ResolucionInstitucionalId");

                    b.HasIndex("TipoAutorizacionId");

                    b.ToTable("SolicitudesAutorizacion");
                });

            modelBuilder.Entity("Indotel.Core.Models.SolicitudCertificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ComentarioRevision")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRechazo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRenovacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRevision")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoRechazo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroSolicitud")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("PrestadoraId")
                        .HasColumnType("int");

                    b.Property<int?>("ResolucionInstitucionalId")
                        .HasColumnType("int");

                    b.Property<string>("SolicitanteNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolicitanteRnc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoCertificacionId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioResponsableId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("NumeroSolicitud")
                        .IsUnique();

                    b.HasIndex("PrestadoraId");

                    b.HasIndex("ResolucionInstitucionalId");

                    b.HasIndex("TipoCertificacionId");

                    b.ToTable("SolicitudesCertificacion");
                });

            modelBuilder.Entity("Indotel.Core.Models.TipoAutorizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TiposAutorizacion");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Solicitud para operar o prestar servicios de telecomunicaciones",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Operacion de servicio telecom"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Renovacion de una autorizacion institucional existente",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Renovacion de autorizacion"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Autorizacion regulatoria para pruebas o condiciones tecnicas especiales",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Autorizacion tecnica especial"
                        });
                });

            modelBuilder.Entity("Indotel.Core.Models.TipoCertificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TiposCertificacion");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Certificacion de existencia o registro institucional",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Certificacion de registro"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Certificacion de cumplimiento regulatorio",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Certificacion de cumplimiento"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Certificacion sobre condicion tecnica o documental",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Certificacion tecnica"
                        });
                });

            modelBuilder.Entity("Indotel.Core.Models.TipoReclamacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TiposReclamacion");
                });

            modelBuilder.Entity("Indotel.Core.Models.TipoResolucion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TiposResolucion");
                });

            modelBuilder.Entity("Indotel.Core.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastFailedLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Indotel.Core.Models.AsignacionFrecuencia", b =>
                {
                    b.HasOne("Indotel.Core.Models.FrecuenciaRadioelectrica", "FrecuenciaRadioelectrica")
                        .WithMany()
                        .HasForeignKey("FrecuenciaRadioelectricaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Indotel.Core.Models.Prestadora", "Prestadora")
                        .WithMany()
                        .HasForeignKey("PrestadoraId");

                    b.Navigation("FrecuenciaRadioelectrica");

                    b.Navigation("Prestadora");
                });

            modelBuilder.Entity("Indotel.Core.Models.LicenciaTecnica", b =>
                {
                    b.HasOne("Indotel.Core.Models.FrecuenciaRadioelectrica", "FrecuenciaRadioelectrica")
                        .WithMany()
                        .HasForeignKey("FrecuenciaRadioelectricaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Indotel.Core.Models.Prestadora", "Prestadora")
                        .WithMany()
                        .HasForeignKey("PrestadoraId");

                    b.HasOne("Indotel.Core.Models.ResolucionInstitucional", "ResolucionInstitucional")
                        .WithMany()
                        .HasForeignKey("ResolucionInstitucionalId");

                    b.Navigation("FrecuenciaRadioelectrica");

                    b.Navigation("Prestadora");

                    b.Navigation("ResolucionInstitucional");
                });

            modelBuilder.Entity("Indotel.Core.Models.MotivoReclamacion", b =>
                {
                    b.HasOne("Indotel.Core.Models.TipoReclamacion", "TipoReclamacion")
                        .WithMany()
                        .HasForeignKey("TipoReclamacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoReclamacion");
                });

            modelBuilder.Entity("Indotel.Core.Models.Reclamacion", b =>
                {
                    b.HasOne("Indotel.Core.Models.MotivoReclamacion", "MotivoReclamacion")
                        .WithMany()
                        .HasForeignKey("MotivoReclamacionId");

                    b.HasOne("Indotel.Core.Models.TipoReclamacion", "TipoReclamacion")
                        .WithMany()
                        .HasForeignKey("TipoReclamacionId");

                    b.Navigation("MotivoReclamacion");

                    b.Navigation("TipoReclamacion");
                });

            modelBuilder.Entity("Indotel.Core.Models.RefreshToken", b =>
                {
                    b.HasOne("Indotel.Core.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Indotel.Core.Models.ResolucionInstitucional", b =>
                {
                    b.HasOne("Indotel.Core.Models.DocumentoReclamacion", "DocumentoReclamacion")
                        .WithMany()
                        .HasForeignKey("DocumentoReclamacionId");

                    b.HasOne("Indotel.Core.Models.Prestadora", "Prestadora")
                        .WithMany()
                        .HasForeignKey("PrestadoraId");

                    b.HasOne("Indotel.Core.Models.Reclamacion", "Reclamacion")
                        .WithMany()
                        .HasForeignKey("ReclamacionId");

                    b.HasOne("Indotel.Core.Models.TipoResolucion", "TipoResolucion")
                        .WithMany()
                        .HasForeignKey("TipoResolucionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentoReclamacion");

                    b.Navigation("Prestadora");

                    b.Navigation("Reclamacion");

                    b.Navigation("TipoResolucion");
                });

            modelBuilder.Entity("Indotel.Core.Models.SolicitudAutorizacion", b =>
                {
                    b.HasOne("Indotel.Core.Models.Prestadora", "Prestadora")
                        .WithMany()
                        .HasForeignKey("PrestadoraId");

                    b.HasOne("Indotel.Core.Models.ResolucionInstitucional", "ResolucionInstitucional")
                        .WithMany()
                        .HasForeignKey("ResolucionInstitucionalId");

                    b.HasOne("Indotel.Core.Models.TipoAutorizacion", "TipoAutorizacion")
                        .WithMany()
                        .HasForeignKey("TipoAutorizacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prestadora");

                    b.Navigation("ResolucionInstitucional");

                    b.Navigation("TipoAutorizacion");
                });

            modelBuilder.Entity("Indotel.Core.Models.SolicitudCertificacion", b =>
                {
                    b.HasOne("Indotel.Core.Models.Prestadora", "Prestadora")
                        .WithMany()
                        .HasForeignKey("PrestadoraId");

                    b.HasOne("Indotel.Core.Models.ResolucionInstitucional", "ResolucionInstitucional")
                        .WithMany()
                        .HasForeignKey("ResolucionInstitucionalId");

                    b.HasOne("Indotel.Core.Models.TipoCertificacion", "TipoCertificacion")
                        .WithMany()
                        .HasForeignKey("TipoCertificacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prestadora");

                    b.Navigation("ResolucionInstitucional");

                    b.Navigation("TipoCertificacion");
                });
#pragma warning restore 612, 618
        }
    }
}
